--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sohaib/.local/share/omarchy/themes/ristretto/backgrounds/2-ristretto.jpg"

-- Special
background="#0f0c01"
foreground="#c8bea0"
cursor="#c8bea0"

-- Colors
color0="#0f0c01"
color1="#6A5C1C"
color2="#5D5B37"
color3="#7A7F7D"
color4="#8C6911"
color5="#8D641D"
color6="#8A7652"
color7="#c8bea0"
color8="#8c8570"
color9="#6A5C1C"
color10="#5D5B37"
color11="#7A7F7D"
color12="#8C6911"
color13="#8D641D"
color14="#8A7652"
color15="#c8bea0"
